1. add dropEvent
juzzlin/Heimer pull request #160
Opened 2021-05-25 07:20 UTC by BeyondXinXin

2021-05-25 07:24 UTC, BeyondXinXin commented
Came across this great project，This interaction is the best I've ever met.
Thanks for sharing.

When I drag "*.Alz" to the main screen, I find it can not be opened.

2021-05-26 09:55 UTC, juzzlin commented
Cool! I'll check and test this soon :)

2021-05-27 07:34 UTC, juzzlin requested changes
Seems to work, but I noticed one bigger issue: if we have a modified mind map and we drag'n'drop a new one Heimer doesn't say that the current mind map is changed - it just replaces the active mind map with the new one. I guess that this should work like opening a new mind map in this case.

2021-05-27 07:34 UTC, juzzlin commented on src/application.cpp
> +﻿// This file is part of Heimer.
Not sure what's changed here? BOM?

2021-05-27 07:34 UTC, juzzlin commented on src/editor_view.hpp
> +    QString m_dropFile{};
{} not needed

2021-05-27 07:34 UTC, juzzlin commented on src/editor_view.hpp
> +    void dropEvent(QDropEvent *event) override;
Placement of '*' is incorrect. Please use `src/.clang-format`.

2021-05-27 08:34 UTC, BeyondXinXin commented
I'm still a beginner, thanks for pointing out the mistakes.

2021-05-27 08:38 UTC, juzzlin commented
Sorry for being a bit unresponsive, but I've been super busy this week. I still want to have this merged, so no worries :)

2021-05-27 16:52 UTC, juzzlin commented
I squashed your commits into a single commit and pushed to master now. This was very good work! Thank you very much! :)

2021-05-27 16:52 UTC, closed without merging